### ISSUE TITLE
Optimizing paramaters

### ISSUE THREAD

**Issue by Hazelfire** [silentcoder99/Hex-DLC#10]
My fork of this repo is just about as optimized as I can make it. But I would like to set some parameters and keep coding it while it runs.

I could make it pass the population between the different versions of the server. For instance, once I make a change on Github, my server can pull the change, compile it, grab the population from the server, stop the server, load the new server and continue using the population.

Time isn't an issue here, but I'm more concerned with the size of the layers. I don't know too much about Neuron networks but in my eyes the more neurons the more it can learn about the game.

I'll be working on said automatic server right now. 

My code takes 0.04 seconds to complete a generation with the current config, including printing, so it is likely to be faster than that in reality.

**Comment by Hazelfire** [comment]
Also, I was thinking, I because of how the network works with decimal weights, would it be better to represent the tiles on the board as:
-1: enemy
0: empty
1: ours

That way it works be easier to make a distinction (I think), because the weights are in order of how "friendly" they are

Just a thought

**Comment by silentcoder99** [comment]
Regarding layer sizes, I do think the size of the network will need to be increased. As for the exact size, I think we'll just have to experiment to find the smallest size that still plays well (as using an unnecessarily large network just means more weights need to be evolved). Although from what I've seen from other people's work , I'd say it would be worth trying something around a 50, 20 network (50 neurons in first layer, 20 in the second).

I've also been thinking about changing the network inputs, and I think your idea could work well, as it already fits within the range of the network's weights, and it means there's a larger difference between the friendly and enemy state, as well as being ordered in some way.
