### ISSUE TITLE
C++ Client preview of game

### ISSUE THREAD

**Issue by Hazelfire** [silentcoder99/Hex-DLC#13]
Would it be a bit too much to add a preview of a game between two players on the server from within the client? This wouldn't be easy... and we might need to be working on other things...

Your call Michael!

**Comment by silentcoder99** [comment]
I think once population packaging and bench marking are completed, if we decide to add them, I think it would be worth it, as it would be something we could use when working with convolutional networks as well. However, it depends on what you where thinking of implementing. I think something as simple as what we've used before (printing all moves to a text file) would be enough, although I'm not sure how hard it would be to implement even that.

**Comment by Hazelfire** [comment]
No, just printing it would not be too hard, but it also means that the client would need to know how to read networks and play the game, which adds a lot of functionality to the client.

Or the entire game could be sent over the network instead, this would be a very long message but would make it super easy to implement

**Comment by silentcoder99** [comment]
If sending the whole game doesn't work very well, then we could run the game from the client, but otherwise, I think keeping it simple for now would be best, as it would still be easier than transferring everything over to the hex site.

**Comment by Hazelfire** [comment]
That would be easier, it wouldn't even require any changes to the code on the client side.
I'll work on this after I finish packaging metadata
