### ISSUE TITLE
Mutation Rate is way too high

### ISSUE THREAD

**Issue by Hazelfire** [silentcoder99/Hex-DLC#14]
if every 5th element gets mutated every generation, how will the networks evolve?

I'm not the neuron network expert, but I think that 0.2 is way too high, and it should be something like 0.001

**Comment by Hazelfire** [comment]
According to [this](http://www.obitko.com/tutorials/genetic-algorithms/recommendations.php) website, I think 0.2 is meant to be a percentage, do you want me to make it interpreted as a percentage in the code?

**Comment by silentcoder99** [comment]
Yeah, that sounds better.
