### ISSUE TITLE
Use REST instead of Websockets

### ISSUE THREAD

**Issue by Hazelfire** [silentcoder99/Hex-DLC#15]
Currently the protocol used for communicating with the server is Websockets. This is when the client and the server can communicate bidirectionally to each other. A more lightweight approach to implementing the server is rest, which is when the client asks for information and the server just responds. The difference is that the server can not initiate any messages.

Rest is more suited to this project. But swapping over entails using a better solution than a solution that already works. So I'm just asking whether this would be worth the effort.

If we used REST, if would be much easier for JS programmers like @retroverse to interface the server within their own applications.

**Comment by silentcoder99** [comment]
I think making this more accessible to other programmers, especially those already interested in Hex, would be great, so I'm fine with it.

**Comment by giraugh** [comment]
Unfortunately though, the thing i originally discussed about fetching the weights directly from the bot whilst not being impossible is very hard due to the _cross origin policy_ which prevents making AJAX calls to different servers. However it is possible to load certain resources by setting their `src` property to the url however this is really convoluted and requires work on the server side, look up JSONP (Json with Padding) 

This time i put this in the right issue!

**Comment by Hazelfire** [comment]
You should be able to communicate using HTTP  GET and POST requests, I'm not sure if that's synonymous with AJAX, but I found a StackOverflow thread [here](http://stackoverflow.com/questions/247483/http-get-request-in-javascript) that might give you a heads up, and may be simpler than AJAX

**Comment by Hazelfire** [comment]
I'm working on implementing this right now, and I realised that accessing this server is easier than you might think.

A GET request is a normal request to a website. This means that if you are running the server, you can literally navigate `http://localhost:20046/champ` on a browser and have all the weights!

POST requests are done by adding `?key=value&otherkey=othervalue` to the end on the url, for example `http://localhost:20046/gencount?count=100` will set the count to 100 and `http://localhost:20046/gencount` will return the count

**Comment by giraugh** [comment]
Nice! How do we access it now? The same as above?

**Comment by Hazelfire** [comment]
Well, you need to compile and run it... I might create a server for you to play with if you want soon, and then you can access it with `hazelfire.org/champ`
