### ISSUE TITLE
Remotely stopping the server

### ISSUE THREAD

**Issue by Hazelfire** [silentcoder99/Hex-DLC#18]
Now that we are using REST for the server, I have removed the ability to stop it remotely because it would have been way to easy to do, anyone could stop any server.

Even though Hex-DLC is not very security-based, anyone being able to stop the server goes against my coding morals, so if I were to implement remote stopping again, there would need to be a randomly generated passphrase made at application startup sent with the stop request.

Is such a thing even worth doing? You could always stop the server by killing the application/container via SSH or locally if you wanted to... Integrating it with the application would just give a web interface to stopping the server. Does @retroverse ever need to stop the server via the REST interface?

**Comment by giraugh** [comment]
Don't think so

**Comment by silentcoder99** [comment]
If you can use SSH to remotely shut off the server, I don't think it will be necessary to add it to the web interface for now.

**Comment by Hazelfire** [comment]
Guess we won't be doing it for now
