### ISSUE TITLE
The Great Bug Hunt

### ISSUE THREAD

**Issue by silentcoder99** [silentcoder99/Hex-DLC#9]
Find all the bugs!

**Comment by Hazelfire** [comment]
I found an interesting piece of code.
In the network constructor, it adds m_numHiddenLayers - 1 hidden layers and adds an input and an output layer. Should it be an input, an output and m_numHiddenLayers hidden layers?

**Comment by Hazelfire** [comment]
I'm also not 100% sure about the numWeights, as it is +1 due to the bias, but I am not sure if the setWeights function understands that

**Comment by silentcoder99** [comment]
For the network constructor, the first layer added is a hidden layer, inputs aren't considered a layer in this network. The reason it is created separate from the rest is that all other layers can get their number of inputs from the previous layer, but the first layer doesn't have a previous layer, and must be defined using the number of network inputs.


As for the the setWeights function, numWeights is the exact amount of weights needed to be given to a neuron. While the number of inputs is one less, the bias acts as an extra input to the neuron, requiring it's own weight to be added during setWeights. The same is also done in the neuron constructor.

**Comment by Hazelfire** [comment]
You're right, I don't think there are any bugs there.

However, the win reward is 0, enough said.

Also, the output from the network should be between -1 and 1. So how is it that when you *11 and floor the result is between 0 and 10?

**Comment by Hazelfire** [comment]
Ok, forget I said that last point, the sigmoid is between 0 and 1, sorry...

**Comment by Hazelfire** [comment]
Could I call this closed?

**Comment by silentcoder99** [comment]
Yeah, that should be fine
